version : '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports: 
      - "81:81"
    volumes:
      - ./nginx_server:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    container_name: application
    command: bash -c "gunicorn -b 0.0.0.0:5000 app:app"
    volumes:
      - .:/opt/application
    expose:
      - "5000"
    env_file:
      - dev_conf.env
    restart: always
